language: node_js
node_js:
 - 12

services:
 - docker

install:
 - echo "nothing needs to be installed"

before_script:
 - echo "no tests"

## Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
## Use either `docker-compose` or individual `docker build` commands
## Build
script:
  - docker build -t udagram-api-feed ./project/udagram-api-feed
  - docker build -t udagram-api-user ./project/udagram-api-user
  - docker build -t udagram-frontend ./project/udagram-frontend
  - docker build -t reverseproxy ./project/udagram-reverseproxy
## Do similar for other three images

## Tagging
  - docker tag udagram-api-feed sonya2404/udagram-api-feed:v1
  - docker tag udagram-api-user sonya2404/udagram-api-user:v1
  - docker tag udagram-frontend sonya2404/udagram-frontend:v1
  - docker tag reverseproxy sonya2404/reverseproxy:v1
## Do similar for other three images```

## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sonya2404/udagram-api-feed:v1
  - docker push sonya2404/udagram-api-user:v1
  - docker push sonya2404/udagram-frontend:v1
  - docker push sonya2404/reverseproxy:v1
## Do similar for other three images